### ISSUE TITLE
Add cross symbol "†" representing an extinct taxon

### ISSUE THREAD

**Issue by dorrhound** [gbif/text-tree#3]
Maybe we can use cross symbol "†" to show extinct taxa in text tree, just like what is done in former website:
[https://www.catalogueoflife.org/annual-checklist/2019/browse/tree](url)
It doesn't take much space, but helps a lot. 

![image](https://github.com/gbif/text-tree/assets/128362476/fd44b72b-4e69-49ea-b929-c5447218ef6a)

(By the way, I noticed the dinosaurs are removed in the newest version of COL. Maybe it's because they're hard to categorize. Looking forward to their return.)
Thank you!

**Comment by mdoering** [comment]
I like that idea, together with using `=` and `≡` for the [synonyms](https://github.com/gbif/text-tree/issues/2).
It needs a bit of adaptations on the COL API side of things, but the library should be handle this rather easily
